service: pv-slsfirstservice

plugins:
  - serverless-prune-plugin

custom: ${file(./variables.yml)}

resources: ${file(./resources.yml)}

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  role: DynamoDBAll
  stage: dev
  versionLambda: false
package:
  individually: true  
  exclude:    
    - '**/*'
  include:      
    - node_modules/**
    - types/*.js
functions:
  pvtest:
    package:
      include:     
        - pvtest.js
    handler: pvtest.handler
